[widgets]
name = "Widgets"
columns = 3
[[widgets.services]]
title = "QuickLinks"
name = "QuickLinks"
widget.name = "QuickLinks"
widget.config.link_0_title = "GitHub"
widget.config.link_0_url = "https://github.com/veirt"
widget.config.link_0_icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/github.svg"
widget.config.link_1_title = "Personal Website"
widget.config.link_1_url = "https://veirt.is-a.dev"
widget.config.link_1_icon = "https://veirt.is-a.dev/favicon.ico"
width = 1
height = 3
[[widgets.services]]
widget = { name = "Clock" }
title = "Clock"
width = 1
height = 3
[[widgets.services]]
title = "Weather"
widget = { name = "Weather", config = { latitude = "0.5016", longitude = "117.1265", units = "celsius", refresh_interval = "600" } }
width = 1
height = 3
[[widgets.services]]
title = "System Stats"
widget = { name = "SystemStats", config = { refresh_interval = "5" } }
width = 3
height = 3

[media]
name = "Media"
columns = 6

[[media.services]]
title = "Jellyfin"
href = "https://jellyfin.veirt.moe"
imgSrc = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/jellyfin.svg"
ping = { url = "https://jellyfin.veirt.moe" }
[[media.services]]
title = "Jellyseerr"
href = "https://jellyseerr.veirt.moe"
imgSrc = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/jellyseerr.svg"
ping = { url = "https://jellyseerr.veirt.moe" }
[[media.services]]
title = "Sonarr"
imgSrc = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/sonarr.svg"
href = "https://sonarr.veirt.moe"
ping = { url = "https://sonarr.veirt.moe" }
[[media.services]]
title = "Prowlarr"
href = "https://prowlarr.veirt.moe"
imgSrc = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/prowlarr.svg"
ping = { url = "https://prowlarr.veirt.moe" }
[[media.services]]
title = "qBittorrent"
href = "https://qb.veirt.moe"
imgSrc = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/qbittorrent.svg"
ping = { url = "https://qb.veirt.moe" }
[[media.services]]
title = "ShokoServer"
href = "https://shoko.veirt.moe"
imgSrc = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/shoko.svg"
ping = { url = "https://shoko.veirt.moe" }
[[media.services]]
title = "MeTube"
href = "https://metube.veirt.moe"
imgSrc = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/metube.svg"
ping = { url = "https://metube.veirt.moe" }
[[media.services]]
title = "AniDown"
href = "https://anidown.veirt.moe"
imgSrc = "https://public.veirt.moe/vesta/icons/anidown.png"
ping = { url = "https://anidown.veirt.moe" }
[[media.services]]
title = "miyo"
href = "http://miyo.veirt.moe"
imgSrc = "https://public.veirt.moe/vesta/icons/miyo.png"
ping = { url = "http://miyo.veirt.moe" }
